version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./init-dump:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: exam
      MYSQL_DATABASE: exam
      MYSQL_USER: agne
      MYSQL_PASSWORD: exam

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080